### ISSUE TITLE
Season of Discovery support

### ISSUE THREAD

**Issue by trying-to-function** [GovtGeek/Outfitter#17]
Continuing https://github.com/cdmichaelb/Outfitter/issues/158#issuecomment-1951469883.

> There's a branch that I've tried to consolidate to work in all versions. I haven't dug into SoD, so I know there are issues with the character frame button position.

I previously found this fork but didn't see the [GovtGeek/Outfitter/retail-merge-10.0.5.2](https://github.com/GovtGeek/Outfitter/tree/retail-merge-10.0.5.2) branch.

I've since tested the branch on SoD but it doesn't swap any gear. I am sure there are other issues I did not see as well. If you ever fix it for SoD, please respond to this issue.

Thank you!

**Comment by GovtGeek** [comment]
I'm looking into it now. I have a tentative fix for the button display and frame overlapping. If there are specific bugs you have, individual tickets would be great.

**Comment by GovtGeek** [comment]
I think it's working with SOD now. Try the 3.4.3.3 release.

**Comment by rygarstrong** [comment]
firstly thank you so much. it has more features then i could ever need. question i remember outfitter having stances for warriors e.g in def stance sword and shield equipped. i can physically  click on the bar with the outfits i have no idea how to bind them but its not changing stances if that makes sense. so if i have a macro for cast taunt change stance i will taunt but my gear stays as if its in arms. u just need the 3 stance options added or perhaps its there somewhere ?

**Comment by GovtGeek** [comment]
Can I assume that the 3.4.3.3 release worked for you? I'd like to close this issue if it did.

**Comment by rygarstrong** [comment]
Hello again legend. There are no stance options in the current version. issue still present.

.

**Comment by rygarstrong** [comment]
also when u download 3.4.3.3 in game the version is listed as 3.4.2.3

**Comment by GovtGeek** [comment]
The .toc files have been updated to reflect the current versions of WoW.
Gear swapping is working in SoD.
Outfitter and Rune buttons should no longer overlap in SoD.
The in-game version of Outfitter is updated and will be 3.4.3.4 for the next release.
Warrior stance issue is now it's own issue (#21).
