### ISSUE TITLE
WoWUp support

### ISSUE THREAD

**Issue by Cephel** [GovtGeek/Outfitter#18]
One method could be importing the Github action from https://github.com/BigWigsMods/packager

**Comment by GovtGeek** [comment]
I took a quick look at WoWUp. I added tags to this repository. From what I saw, that should get WoWUp to recognize and pull it. Give it a day and let me know.

**Comment by Cephel** [comment]
Doesn't seem to work unfortunately.

**Comment by GovtGeek** [comment]
Are you doing the basic search or are you using the Install from URL option?

**Comment by Cephel** [comment]
I tried it again and it works now
