### ISSUE TITLE
WOTLK - Error when loading the addon on a druid

### ISSUE THREAD

**Issue by Cephel** [GovtGeek/Outfitter#24]
![image](https://github.com/GovtGeek/Outfitter/assets/6716857/640ea0a4-18e3-4573-aa84-cf32cd45a3d5)

Seems to happen with the scripted outfits being enabled:
![image](https://github.com/GovtGeek/Outfitter/assets/6716857/987710e9-7fb7-416d-ab66-b607b3830fcc)

**Comment by GovtGeek** [comment]
I can't see enough of the error to really know if it's fixed, but I just realesed 4.4.0.0 with a lot of updates.
