### ISSUE TITLE
CATA - Primary & Secondary Talent Automation

### ISSUE THREAD

**Issue by Aetherdan** [GovtGeek/Outfitter#26]
The automation options for primary and secondary talent automation aren't available for Classic Cataclysm. Is this a limitation with the forking of the addon or is this something that was missed?

**Comment by DanSheps** [comment]
You can do a custom script for this:

```lua
-- $EVENTS ACTIVE_TALENT_GROUP_CHANGED
-- $DESC Equips event on Spec Change
-- $SETTING spec={Label="Spec", Type="Number"}

if not isEquipped and GetActiveTalentGroup() == setting.spec then
    print('Equipping Outfit "' .. outfit.Name .. '"')
    equip = true
else
    return
end
```

Then there will be a setting for the "spec", you would choose "1" for the Primary spec and "2" for the Secondary spec

**Comment by GovtGeek** [comment]
Just an update for here. It's still on my list. Since the workaround has been here, it hasn't been high priority. Hopefully soon.
