### ISSUE TITLE
[Cataclysm Classic] Gear slot flyouts are missing

### ISSUE THREAD

**Issue by AlexFolland** [GovtGeek/Outfitter#28]
Gear slot flyouts (known as "Quickslots" in Outfitter's terminology) as pictured on the CurseForge project for Outfitter are missing from this project.  Here's the image from CurseForge.

![](https://media.forgecdn.net/attachments/94/993/Quickslots.png)

These would usually be visible and usable while holding an item from the character menu on the mouse cursor.

I used to use these constantly when changing gear, and now that they're gone, I really miss them.  I don't know when it happened exactly since Outfitter wasn't working for a long time, and then I more-recently installed your fork, and I don't see the gear flyouts.

Thank you for forking this and for your maintainership.

**Comment by GovtGeek** [comment]
Those Quickslot flyouts show for me when I hold the 'Alt' key. It's part of the default UI. Is that not working for you? Are you expecting the quickslots to display whenever you hover?

**Comment by AlexFolland** [comment]
I'm expecting the original behavior of Outfitter which was present for more than 10 years from 2005 to at least 2016: the flyout to be visible while the gear item is on the cursor.  It was intuitive and beautiful, looking just like the image posted in my first comment here and not needing any keyboard presses.

I see something when pressing the Alt key, but this thing is way worse than Outfitter's original gear flyout which comes up when an item is picked up, clearly shows an empty bag slot, and doesn't show other items that are already equipped.  Clicking while the Alt key is held down doesn't let me pick up the item anyway.  The original gear flyout is ideal.

**Comment by GovtGeek** [comment]
I'll see what I can do. A lot changed underneath, but there's still some code I've seen mentioning the flyouts.

**Comment by GovtGeek** [comment]
@AlexFolland There's a beta version that I think gives you what you want. Try the 4.4.0.5-beta-01 (https://github.com/GovtGeek/Outfitter/commit/74cec8295bfc05c0b66942f8e955fc41764e48ab) release and let me know if that's what you were expecting.

**Comment by AlexFolland** [comment]
Yes, this is almost exactly it!  Thank you!  The only differences are the vertical centering, the yellow border, and the empty bag slot not looking truly empty, but all of those are minor nitpicks.  I'm happy with this.  Thank you very much!

**Comment by GovtGeek** [comment]
Great. I'll get it integrated into the full release after I get some testing down with Classic Era/SoD and Retail.
