### ISSUE TITLE
WoW SoD - Error

### ISSUE THREAD

**Issue by Roktak** [GovtGeek/Outfitter#30]
Message: bad argument #2 to '?' (Usage: local success = C_CVar.SetCVarBitfield(name, index, value [, scriptCVar]))
Time: Thu Jul 18 10:30:56 2024
Count: 1
Stack: bad argument #2 to '?' (Usage: local success = C_CVar.SetCVarBitfield(name, index, value [, scriptCVar]))
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...las/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Attune/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ace/AddOns/Attune/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/Blizzard_UIParent/Vanilla/UIParent.lua"]:227: in function `UIParentLoadAddOn'
[string "@Interface/AddOns/Blizzard_UIParent/Vanilla/UIParent.lua"]:298: in function `TimeManager_LoadUI'
[string "@Interface/AddOns/Blizzard_UIParent/Vanilla/UIParent.lua"]:540: in function <...erface/AddOns/Blizzard_UIParent/Vanilla/UIParent.lua:509>

Locals: Lib = <table> {
 Loading = <table> {
 }
 Embed = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:113
 NewAddon = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:106
}
safecall = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:18
tremove = <function> defined =[C]:-1

**Comment by Roktak** [comment]
This come only when Outfitter is active under Addons

**Comment by GovtGeek** [comment]
The errors are coming from BagBrother, Atlas, and Blizzard_UIParent. Do you get errors if you disable those addons?

**Comment by Roktak** [comment]
When i disable BagBrother is the LUA Error gone.

**Comment by GovtGeek** [comment]
Identified as BagBrother issue.
