### ISSUE TITLE
Attempt to Compare - SOD

### ISSUE THREAD

**Issue by MetalJacx** [GovtGeek/Outfitter#31]
Message: Interface/AddOns/Outfitter/OutfitterInventory.lua:409: attempt to compare number with nil
Time: Wed Jul 24 10:27:43 2024
Count: 107
Stack: Interface/AddOns/Outfitter/OutfitterInventory.lua:409: attempt to compare number with nil
[string "@Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua"]:172: in function <...tCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:170>
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Outfitter/OutfitterInventory.lua"]:409: in function `GetItemInfoFromLink'
[string "@Interface/AddOns/Outfitter/OutfitterInventory.lua"]:250: in function `GetItemInfoFromLink'
[string "@Interface/AddOns/Outfitter/Outfitter.lua"]:7095: in function <Interface/AddOns/Outfitter/Outfitter.lua:7092>
[string "=[C]"]: in function `SetHyperlink'
[string "@Interface/AddOns/ClassicLootManager/Modules/GUI/UnifiedGUI_History.lua"]:163: in function <...lassicLootManager/Modules/GUI/UnifiedGUI_History.lua:160>
[string "@Interface/AddOns/ClassicLootManager/Modules/GUI/UnifiedGUI_History.lua"]:298: in function `handler'
[string "@Interface/AddOns/ClassicLootManager/Libs/lib-st/Core.lua"]:66: in function `FireUserEvent'
[string "@Interface/AddOns/ClassicLootManager/Libs/lib-st/Core.lua"]:94: in function <...rface/AddOns/ClassicLootManager/Libs/lib-st/Core.lua:92>

Locals: private = <table> {
 ThrowError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:71
 DoesErrorExist = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:112
 ClearOldErrors = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:133
 SanitizeLine = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:108
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:142
 IncrementErrorCount = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:102
 NewError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:75
 IsRCLootCouncilError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:119
}
orig_errorhandler = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedBasicControls.lua:363

**Comment by GovtGeek** [comment]
Can you recreate the error without RCLootCouncil enabled?

**Comment by GovtGeek** [comment]
Without extra information, I'm going to assume this isn't an issue anymore.
