### ISSUE TITLE
Lua Errors in Classic Era

### ISSUE THREAD

**Issue by Gogo1951** [GovtGeek/Outfitter#34]
I feel like you've done a great job helping this add-on limp along. And I'd be lost without it.

But looking at how many XML and Lua errors just popped up, I have a feeling this may be the end of the line without a bit of a re-write. 

Thanks for maintaining this!

**Comment by GovtGeek** [comment]
Blizzard has been doing a lot of movement underneath. They're changing some very structural pieces and finally removing some deprecated code. It's just not obvious when they're going to remove some of those pieces.

I still depend heavily on the bug reports, especially in Classic (includes SOD) and Retail.

**Comment by Gogo1951** [comment]
<img width="627" alt="image" src="https://github.com/user-attachments/assets/060bf897-65f5-45ff-933a-a0ec1e0f2802">

And when you go to use the menu.

17x ...rfaceOutfitter/Libraries/LibDropdown-1.0.lua:215: attempt to call upvalue 'GetMouseFocus' (a nil value)
[string "@Outfitter/Libraries/LibDropdown-1.0.lua"]:215: in function <...rfaceOutfitter/Libraries/LibDropdown-1.0.lua:214>
[string "@Outfitter/Libraries/LibDropdown-1.0.lua"]:280: in function <...rfaceOutfitter/Libraries/LibDropdown-1.0.lua:278>

Locals:
frame = Button {
 handled = true
 released = false
 data = <table> {
 }
 dataname = 3
 PixelSnapDisabled = true
 expand = Texture {
 }
 enabled = true
 clickable = false
 group = <table> {
 }
 option = <table> {
 }
 text = FontString {
 }
 groupFrame = LibDropdownFrame1 {
 }
 swatch = Button {
 }
 parentTree = <table> {
 }
 check = Texture {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetMouseFocus' (a nil value)"
GetMouseFocus = nil
UIParent = UIParent {
 firstTimeLoaded = 1
 variablesLoaded = true
}

**Comment by GovtGeek** [comment]
Check out the beta versions I have available.

**Comment by Gogo1951** [comment]
Seems to work great, apologies I should have checked the beta builds!
